### ISSUE TITLE
se solicita validar valor de retorno del metodo  destroy del resource

### ISSUE THREAD

**Issue by jjanampa** [weblabormx/laravel-front#12]
Hay casos en los que en la eliminacion se debe validar el registro,dependiendo del resultado  debe permitir o no  que siga con el proceso de eliminacion.
- esto es lo que se tiene:
![image](https://github.com/weblabormx/laravel-front/assets/1957176/295e62c6-e94a-4bce-a62c-676342c2f841)

- asi podria quedar:
![image](https://github.com/weblabormx/laravel-front/assets/1957176/1b6a01c6-aef1-4ee5-a534-b1ed295929ab)

**Comment by jjanampa** [comment]
se esta enviando este PR: https://github.com/weblabormx/laravel-front/pull/14

**Comment by skalero01** [comment]
Listo, pull request aceptado
